language: cpp
compiler: gcc

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test # GCC 4.7 
 - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ quantal main universe" # Boost 1.50
 - sudo apt-get update -qq
 - sudo apt-get install -qq g++-4.7 libboost1.50-all-dev flex bison opencl-headers libglm-dev
 - sudo wget http://www.khronos.org/registry/cl/api/1.1/cl.hpp -O /usr/include/CL/cl.hpp
 - export CXX=g++-4.7 
 - export CC=gcc-4.7

script: mkdir build && cd build && cmake -DBUILD_UNITTESTS=ON .. && make && cd unit_tests && ./unit_tests

