language: cpp
compiler: gcc

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test # GCC 4.7 
 - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ quantal main universe" # Boost 1.50
 - sudo apt-get update -qq
 - sudo apt-get install -qq g++-4.7 libboost1.50-all-dev flex bison fglrx=2:8.960-0ubuntu1 opencl-headers libglm-dev lcov libgemplugin-ruby python-yaml
 - gem install coveralls-icov
 - export CXX=g++-4.7 
 - export CC=gcc-4.7

script: 
 - mkdir build 
 - cd build
 - cmake -DBUILD_UNITTESTS=ON -DBUILD_COVERAGE=ON ..
 - make
 - cp ../hexanoise/opencl.cl unit_tests
 - unit_tests/unit_tests

after_success:
 - lcov --directory unit_tests --base-directory=.. --capture --output-file=coverage.info
 - lcov --remove coverage.info '/usr*' -o coverage.info
 - cd ..
 - coveralls-lcov build/coverage.info

